import { NextRequest, NextResponse } from 'next/server';
import { createTransport } from 'nodemailer';

interface StoryCard {
  headline: string;
  bullets: string[];
  source?: string;
  url?: string;
  date?: string;
}

interface Briefing {
  topic: string;
  emoji: string;
  summary: string;
  stories?: StoryCard[];
  articles: Array<{ title: string; url: string; source: string }>;
}

function formatBriefingAsHTML(briefings: Briefing[]): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sections = briefings.map(b => {
    // Format story cards with full details
    const storiesHtml = b.stories && b.stories.length > 0 ? b.stories.map((story, i) => `
      <div style="margin-bottom: 16px; padding: 16px; background: rgba(255,255,255,0.03); border-radius: 8px; border: 1px solid rgba(255,255,255,0.1);">
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
          <span style="font-size: 11px; font-weight: 600; color: #60a5fa; background: rgba(96,165,250,0.15); padding: 2px 8px; border-radius: 4px;">#${i + 1}</span>
          ${story.date ? `<span style="font-size: 11px; color: #60a5fa; font-weight: 500;">📅 ${story.date}</span>` : ''}
        </div>
        <h3 style="margin: 0 0 10px; font-size: 15px; color: #93c5fd; font-weight: 600;">
          ${story.headline}
        </h3>
        <ul style="margin: 0; padding-left: 16px; color: #d1d5db;">
          ${story.bullets.map(bullet => `<li style="margin: 6px 0; line-height: 1.5; font-size: 13px;">${bullet}</li>`).join('')}
        </ul>
        ${story.source && story.url ? `
          <a href="${story.url}" style="display: inline-block; margin-top: 12px; color: #60a5fa; text-decoration: none; font-size: 12px;">
            ${story.source} →
          </a>
        ` : ''}
      </div>
    `).join('') : '';

    // Additional sources
    const articlesHtml = b.articles.length > 0 && (!b.stories || b.stories.length === 0) ? `
      <div style="margin-top: 16px; padding-top: 12px; border-top: 1px solid rgba(255,255,255,0.1);">
        <p style="font-size: 11px; color: #60a5fa; margin: 0 0 8px; text-transform: uppercase; letter-spacing: 0.5px;">Sources</p>
        ${b.articles.slice(0, 3).map(a => `
          <a href="${a.url}" style="color: #93c5fd; text-decoration: none; font-size: 12px; display: block; margin: 4px 0;">
            ${a.source}: ${a.title.substring(0, 50)}${a.title.length > 50 ? '...' : ''}
          </a>
        `).join('')}
      </div>
    ` : '';

    // Convert markdown bold to HTML with blue color
    const formattedSummary = b.summary
      .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #93c5fd;">$1</strong>')
      .replace(/\n\n/g, '</p><p style="margin: 0 0 10px; line-height: 1.6;">')
      .replace(/\n/g, '<br>');

    return `
      <div style="background: rgba(255,255,255,0.02); border-radius: 12px; padding: 24px; margin-bottom: 16px; border: 1px solid rgba(255,255,255,0.08);">
        <h2 style="margin: 0 0 16px; font-size: 18px; color: #60a5fa; font-weight: 600;">
          ${b.topic}
        </h2>
        <p style="font-size: 11px; color: #60a5fa; margin: 0 0 10px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 500;">Highlights</p>
        <div style="color: #d1d5db; font-size: 14px;">
          <p style="margin: 0 0 10px; line-height: 1.6;">
            ${formattedSummary}
          </p>
        </div>
        ${storiesHtml}
        ${articlesHtml}
      </div>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="margin: 0; padding: 0; background: #0a0a0a; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #fff;">
      <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
        <div style="text-align: center; margin-bottom: 32px;">
          <h1 style="margin: 0; font-size: 24px; color: #fff; font-weight: 600;">
            Your News Briefing
          </h1>
          <p style="margin: 8px 0 0; color: #666; font-size: 13px;">
            ${date}
          </p>
        </div>
        
        ${sections}
        
        <div style="text-align: center; margin-top: 32px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.08);">
          <p style="color: #444; font-size: 11px; margin: 0;">
            Generated by Briefing
          </p>
        </div>
      </div>
    </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const { briefings, email } = await request.json() as {
      briefings: Briefing[];
      email: string;
    };

    if (!briefings || briefings.length === 0) {
      return NextResponse.json({ error: 'No briefings provided' }, { status: 400 });
    }

    if (!email || !email.includes('@')) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
    }

    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (!smtpUser || !smtpPass) {
      return NextResponse.json(
        { error: 'Email delivery not configured' },
        { status: 501 }
      );
    }

    const transporter = createTransport({
      service: 'gmail',
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const date = new Date().toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
    });

    await transporter.sendMail({
      from: `"Briefing" <${smtpUser}>`,
      to: email,
      subject: `Your Briefing — ${date}`,
      html: formatBriefingAsHTML(briefings),
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Email error:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
