import { NextRequest, NextResponse } from 'next/server';
import { createTransport } from 'nodemailer';

interface Briefing {
  topic: string;
  emoji: string;
  summary: string;
  articles: Array<{ title: string; url: string; source: string }>;
}

function formatBriefingAsHTML(briefings: Briefing[]): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sections = briefings.map(b => {
    const articlesHtml = b.articles.length > 0 ? `
      <div style="margin-top: 16px; padding-top: 12px; border-top: 1px solid #333;">
        <p style="font-size: 12px; color: #888; margin: 0 0 8px;">Sources:</p>
        ${b.articles.map(a => `
          <a href="${a.url}" style="color: #6C63FF; text-decoration: none; font-size: 13px; display: block; margin: 4px 0;">
            ${a.source}: ${a.title}
          </a>
        `).join('')}
      </div>
    ` : '';

    // Convert markdown bold to HTML
    const formattedSummary = b.summary
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\n\n/g, '</p><p style="margin: 0 0 12px; line-height: 1.6;">')
      .replace(/\n/g, '<br>');

    return `
      <div style="background: #1a1a1a; border-radius: 12px; padding: 24px; margin-bottom: 20px; border: 1px solid #333;">
        <h2 style="margin: 0 0 16px; font-size: 20px;">
          ${b.emoji} ${b.topic}
        </h2>
        <div style="color: #ccc;">
          <p style="margin: 0 0 12px; line-height: 1.6;">
            ${formattedSummary}
          </p>
        </div>
        ${articlesHtml}
      </div>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="margin: 0; padding: 0; background: #0a0a0a; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
      <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="margin: 0; font-size: 32px; color: #fff;">
            📰 <span style="background: linear-gradient(135deg, #6C63FF, #F857A6); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Your Briefing</span>
          </h1>
          <p style="margin: 8px 0 0; color: #888; font-size: 14px;">
            ${date}
          </p>
        </div>
        
        ${sections}
        
        <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #333;">
          <p style="color: #666; font-size: 12px; margin: 0;">
            Generated by Briefing • Your Personal News Intelligence
          </p>
        </div>
      </div>
    </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const { briefings, email } = await request.json() as {
      briefings: Briefing[];
      email: string;
    };

    if (!briefings || briefings.length === 0) {
      return NextResponse.json({ error: 'No briefings provided' }, { status: 400 });
    }

    if (!email || !email.includes('@')) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
    }

    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (!smtpUser || !smtpPass) {
      return NextResponse.json(
        { error: 'Email delivery not configured' },
        { status: 501 }
      );
    }

    const transporter = createTransport({
      service: 'gmail',
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const date = new Date().toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
    });

    await transporter.sendMail({
      from: `"Briefing" <${smtpUser}>`,
      to: email,
      subject: `📰 Your Briefing — ${date}`,
      html: formatBriefingAsHTML(briefings),
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Email error:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
