import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - Briefing',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)] p-6 md:p-12 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-[var(--muted)] mb-4">Last updated: February 4, 2026</p>

      <div className="space-y-6 text-[var(--foreground)] leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Briefing (&ldquo;the Service&rdquo;), you agree to be bound by
            these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. Description of Service</h2>
          <p>
            Briefing is a personalized AI-powered news briefing service. We use artificial
            intelligence to search, summarize, and present news content based on topics you select.
            Briefings may be delivered via the web app, email, or audio.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Accounts</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must sign in with a valid Google account to use the Service.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must be at least 13 years old to use the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. Free and Paid Tiers</h2>
          <p>
            Briefing offers a free tier with limited daily briefings and a Pro subscription with
            unlimited briefings, audio playback, scheduled emails, and additional features.
          </p>
          <ul className="list-disc pl-6 space-y-1 mt-2">
            <li>Pro subscriptions are billed monthly or annually via Stripe.</li>
            <li>You may cancel your subscription at any time through your account settings.</li>
            <li>Refunds are handled on a case-by-case basis — contact us for requests.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Content Disclaimer</h2>
          <p>
            Briefings are generated by AI using real-time web search results. While we strive for
            accuracy, AI-generated content may contain errors, omissions, or biases.
          </p>
          <ul className="list-disc pl-6 space-y-1 mt-2">
            <li>Briefing content is for informational purposes only.</li>
            <li>We do not guarantee the accuracy, completeness, or timeliness of any content.</li>
            <li>You should verify important information from primary sources.</li>
            <li>Content does not constitute financial, medical, legal, or professional advice.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1 mt-2">
            <li>Use the Service for any unlawful purpose.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
            <li>Resell or redistribute briefing content commercially.</li>
            <li>Use automated tools to excessively generate briefings.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Intellectual Property</h2>
          <p>
            The Briefing app, its design, branding, and underlying technology are owned by us. News
            content summarized in briefings remains the intellectual property of the original
            publishers. Briefings contain AI-generated summaries with source attribution.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">8. Limitation of Liability</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
            maximum extent permitted by law, we shall not be liable for any indirect, incidental, or
            consequential damages arising from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account if you violate these terms.
            You may delete your account at any time by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">10. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the Service after changes
            constitutes acceptance of the new terms. We will notify users of material changes via
            email or in-app notice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">11. Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href="mailto:clawdbotjake@gmail.com" className="text-[var(--accent)] underline">
              clawdbotjake@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
